substitutions:
  name: garou
  static_ip: !secret ip_garou

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml
  
esp32:
  board: az-delivery-devkit-v4

bluetooth_proxy:
  active: true