substitutions:
  name: gazpar
  static_ip: !secret ip_gazpar

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml
  
esp32:
  board: az-delivery-devkit-v4
  
sensor:
  # Consommation gaz
  - platform: pulse_meter
    id: gazpar
    pin:
      number: GPIO23
    unit_of_measurement: "l/mn"
    icon: mdi:fire
    internal_filter_mode: PULSE
    internal_filter: 150ms
    name: "Débit Gaz"
    state_class: measurement
    filters:
      - multiply: 10
    total:
      unit_of_measurement: "m³"
      name: 'Volume Gaz'
      filters:
        - multiply: 0.01
      accuracy_decimals: 2
      icon: mdi:fire
      id: gazpar_gaz_m3
      device_class: "gas"
      on_value:
        - homeassistant.service:
            service: input_number.increment
            data:
              entity_id: input_number.energy_index_gaz
  - platform: homeassistant
    name: "Index compteur"
    id: energy_index_gaz
    entity_id: input_number.energy_index_gaz
    internal: no
    entity_category: diagnostic
    icon: mdi:counter
    unit_of_measurement: "m³"
    accuracy_decimals: 2
      