esphome:
  name: gazpar

esp32:
  board: az-delivery-devkit-v4

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret home_assistant_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.0.3.1
    gateway: 10.0.0.1
    subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gazpar Fallback Hotspot"
    password: !secret ap_password

captive_portal:

###############################################################################
# SENSORS
binary_sensor:
  ############################ BASICS
  - platform: status
    name: "Statut" 
button:
  ############################ BASICS
  - platform: restart
    name: "Reboot"
sensor:
  ############################ BASICS
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    unit_of_measurement: dB
    accuracy_decimals: 0
    force_update: false
    icon: mdi:wifi
  - platform: uptime
    id: uptime_seconds
    name: "Uptime"
    update_interval: 60s
    unit_of_measurement: s
    accuracy_decimals: 0
    force_update: false
    icon: mdi:clock-start
 
  ############################ GAZ
  # Consommation gaz
  - platform: pulse_meter
    id: gazpar
    pin:
      number: GPIO23
    unit_of_measurement: "l/mn"
    icon: mdi:fire
    internal_filter_mode: PULSE
    internal_filter: 150ms
    name: "Débit Gaz"
    state_class: measurement
    filters:
      - multiply: 10
    total:
      unit_of_measurement: "m³"
      name: 'Volume Gaz'
      filters:
        - multiply: 0.01
      accuracy_decimals: 2
      icon: mdi:fire
      id: gazpar_gaz_m3
      device_class: "gas"
      on_value:
        - homeassistant.service:
            service: input_number.increment
            data:
              entity_id: input_number.energy_index_gaz
  - platform: template
    name: "Puissance Gaz"
    lambda: |-
      return id(gazpar_gaz_m3).state * 10.01;
    device_class: energy
    unit_of_measurement: "kWh"
    accuracy_decimals: 3 
    id: gazpar_puissance_gaz
    state_class: total_increasing
  - platform: homeassistant
    name: "Index compteur"
    id: index_compteur
    entity_id: input_number.energy_index_gaz
    internal: no
    entity_category: diagnostic
    icon: mdi:counter
    unit_of_measurement: "m³"
    accuracy_decimals: 2
    