substitutions:
  name: "musy"
  static_ip: !secret ip_musy
  friendly_name: "Muse Luxe"

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml
  raspiaudio.muse-luxe: github://esphome/media-players/raspiaudio-muse-luxe.yaml@main
  
esphome:
  name: ${name}
  name_add_mac_suffix: false
